[platformio]
default_envs = seeed_xiao_esp32c3

[env:seeed_xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200

lib_deps =
    h2zero/NimBLE-Arduino @ ^1.4.1
    madhephaestus/ESP32Servo @ ^1.1.0

upload_port = COM13
monitor_port = COM13




